### PR TITLE
Fix/issue 20

### LINKED ISSUE #13: Enhance User Presentation in UI
Make enhancements to UI to present multiple Users from database

### PR DESCRIPTION
**Pull request by chris-iri**
Closes #13, #20 and #21

### CODE REVIEW

File: src/main/java/com/iri/training/model/Hobby.java [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+
+	public void setHobbyId(final Long hobbyId) { this.hobbyId = hobbyId; }
+
+	public String getHobbyName() { return hobbyName; }
+
+	public void setHobbyName(final String hobbyName) { this.hobbyName = hobbyName; }
+
+	public String getDescription() { return description; }
+
+	public void setDescription(final String description) { this.description = description; }
```
Comment (dionisisvas) [inline src/main/java/com/iri/training/model/Hobby.java:19]: Add a toString() method in all model classes to use for logging purposes (like in the User class in the develop branch)

File: src/main/java/com/iri/training/model/Image.java [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+
+	public void setUserId(final Long userId) { this.userId = userId; }
+
+	public boolean isProfileImg() { return isProfileImg; }
+
+	public void setProfileImg(final boolean profileImg) { isProfileImg = profileImg; }
+
+	public String getImgUri() { return imgUri; }
+
+	public void setImgUri(final String imgUri) { this.imgUri = imgUri; }
```
Comment (dionisisvas) [inline src/main/java/com/iri/training/model/Image.java:24]: Add toString() method

File: src/main/java/com/iri/training/model/User.java [hunk 3]
```diff
@@ -3,103 +3,44 @@
...
-		builder.append("phone");
-		builder.append(phone);
-		builder.append("userID");
-		builder.append(userID);
-		builder.append("age");
-		builder.append(age);
-
-
-		return builder.toString();
-	}
```
Comment (dionisisvas) [inline src/main/java/com/iri/training/model/User.java:103]: Keep the toString() method and add a similar one to the rest of the model classes

File: src/main/java/com/iri/training/repository/HobbyRepositoryImpl.java [hunk 4]
```diff
@@ -0,0 +1,143 @@
...
+			stmt = c.createStatement();
+			String sql = "SELECT * FROM hobbies;";
+			PreparedStatement pst = c.prepareStatement(sql);
+			ResultSet resultSet = pst.executeQuery( );
+
+			while(resultSet.next()) {
+				hobbies.add(new HobbyBuilder()
+					.withHobbyId(resultSet.getLong("hobbyId"))
+					.withHobbyName(resultSet.getString("hobbyName"))
+					.withDescription(resultSet.getString("description"))
```
Comment (dionisisvas) [inline src/main/java/com/iri/training/repository/HobbyRepositoryImpl.java:126]: You will need to follow a similar approach for the new repository classes as in UserRepositoryImpl (from develop branch)

**Review by dionisisvas — COMMENTED** [review]
Check comments
